# Generated by Django 4.1.5 on 2023-02-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sveve", "0002_contact_active_alter_contact_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="source",
            field=models.CharField(max_length=50, null=True, verbose_name="Source"),
        ),
    ]
